biolog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin web pages
    path('admin/', admin.site.urls),
    # User web pages
    path('users/', include('users.urls')),
    # Biolog web pages
    path('', include('biologs.urls')),
]

biologs/urls.py
from django.urls import path
from . import views

# Used in short URLs {% url 'appname:path_name' %}
app_name = 'biologs'

urlpatterns = [
    path('', views.home, name='home'),
    path('boot', views.boot, name='boot'),
    path('terminology/', views.terminology, name='terminology'),
    path('bioposts/', views.bioposts, name='bioposts'),
    path('biopost/<int:biopost_id>/', views.biopost, name='biopost'),
    path('create_biopost/', views.create_biopost, name='create_biopost'),
    path('edit_biopost/<int:biopost_id>/', views.edit_biopost, name='edit_biopost'),
    path('delete_biopost/<int:biopost_id>/', views.delete_biopost, name='delete_biopost'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Default Django authentication urls (like login, logout, etc.)
    path('', include('django.contrib.auth.urls')),

    # My urls (custom logging functionality) (+ url short naming)
    path('register/', views.register, name='register'),
    path('account/', views.account, name='account'),
]

biologs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BiologPost(models.Model):
    """ Represent a post from some biolog. Biolog is accosiated with the author. """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

biologs/forms.py
from django import forms
from .models import BiologPost

class BiopostForm(forms.ModelForm):
    """ Biopost posting form. """
    class Meta:
        model = BiologPost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': 'Text'}

biologs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import BiologPost
from .forms import BiopostForm
from django.http import Http404

# Create your views here.

def home(request):
    return render(request, 'biologs/index.html')

def terminology(request):
    return render(request, 'biologs/terminology.html')

def boot(request):
    return render(request, 'biologs/boot.html')

def bioposts(request):
    biopost_objects = BiologPost.objects.order_by('date_posted')
    context = {'bioposts': biopost_objects}
    return render(request, 'biologs/bioposts.html', context)

@login_required
def biopost(request, biopost_id):
    biopost = BiologPost.objects.get(id=biopost_id)
    context = {'biopost': biopost}
    return render(request, 'biologs/biopost.html', context)

@login_required
def create_biopost(request):
    if request.method == 'GET':
        form = BiopostForm()
        context = {'form': form}
        return render(request, 'biologs/create_biopost.html', context)
    elif request.method == 'POST':
        form = BiopostForm(data=request.POST)
        if form.is_valid():
            created_biopost = form.save(commit=False)
            created_biopost.author = request.user
            created_biopost.save()
            return redirect('biologs:bioposts')
        else:
            context = {'form': form}
            return render(request, 'biologs/create_biopost.html', context)
    else:
        Http404

@login_required
def edit_biopost(request, biopost_id):
    biopost = BiologPost.objects.get(id=biopost_id)
    if biopost.author != request.user:
        raise Http404

    if request.method == 'GET':
        form = BiopostForm(instance=biopost)
        context = {'form': form, 'biopost': biopost}
        return render(request, 'biologs/edit_biopost.html', context)
    elif request.method == 'POST':
        form = BiopostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('biologs:bioposts')
        else:
            context = {'form': form, 'biopost': biopost}
            return render(request, 'biologs/edit_biopost.html', context)
    else:
        raise Http404

@login_required
def delete_biopost(request, biopost_id):
    biopost = BiologPost.objects.get(id=biopost_id)
    if biopost.author != request.user:
        raise Http404

    biopost.delete()
    return redirect('biologs:bioposts')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.http import Http404

# Create your views here.

# No view created for login (Django default)

def register(request):
    """ Custom user registration (needs to implement logic with the registered user).
    Can be called to GET web site/inteface/file or to POST form data.  """
    if request.method == 'GET':
        # Use Django built-in form for registering new users
        form = UserCreationForm()
        # Send form to the template
        context = {'form': form}
        return render(request, 'registration/register.html', context)
    elif request.method == 'POST':
        filled_form = UserCreationForm(request.POST)
        if filled_form.is_valid():
            # CUSTOM USER REGISTRATION LOGIC
            # get the created user
            registered_user = filled_form.save()
            # logic registered user (as django.contrib.auth.models.User)
            login(request, registered_user)
            return redirect('biologs:home') # redirect to URL
        else:
            # Send invalid form message
            context = {'form': filled_form}
            return render(request, 'registration/register.html', context)
    else:
        raise Http404

def account(request):
    """ Responds with account web page. """
    return render(request, 'registration/account.html')

biologs/templates/biologs/base.html
{# Load Django template tag library #}
{% load bootstrap4 %}


<html lang="en">
  <head>
    {# Standard HTML stuff #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Biolog</title>

    {# Load CSS and JavaScript Bootstrap #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}

  </head>

  <body>
    {# Bootstrap navigation panel #}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

      {# Brand text/logo #}
      <a class="navbar-brand" href="{% url 'biologs:home' %}">Biolog</a>

      {# Collapsive button (toggler) #}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {# Navigation in navigation bar #}
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'biologs:bioposts' %}">Bioposts</a> 
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:account' %}">Account</a> 
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a> 
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a> 
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a> 
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {# Main content #}
    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

  </body>
</html>

biologs/templates/biologs/biopost.html
{% extends "biologs/base.html" %}

{% block header %}<h2 class="d-flex">{{ biopost.title }} <small class="font-weight-bold ml-auto">{{ biopost.date_posted|date:'M d, Y' }}</small></h2>{% endblock %}

{% block content %}
  <p>{{ biopost.text|linebreaks }}</p>
  <hr>
  <p> <a class="text-secondary" href="{% url 'biologs:edit_biopost' biopost.id %}">edit post</a> - 
  <a class="text-secondary" href="{% url 'biologs:delete_biopost' biopost.id %}">delete post</a> </p>
{% endblock %}

biologs/templates/biologs/bioposts.html
{% extends "biologs/base.html" %}

{% block header %}<h1>Biolog bioposts</h1>{% endblock %}

{% block content %}
  {% for biopost in bioposts %}
    <div class="card mb-3">
      <h4 class="card-header d-flex">
        {{ biopost.title }}
        <small class="ml-auto">{{ biopost.date_posted|date:'M d, Y' }}</small>
      </h4>

      <div class="card-body">
        {{ biopost.text|linebreaks }}
        <a class="text-secondary" href="{% url 'biologs:biopost' biopost.id %}">view full post</a>
      </div>
    </div>
  {% empty%}
    <p>No bioposts posted yet.</p>
  {% endfor %}

  <h3> <a href="{% url 'biologs:create_biopost' %}">create your biopost!</a> </h3>
{% endblock %}

biologs/templates/biologs/boot.html
{% load static %}
{% load bootstrap4 %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Biolog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">

      {# Brand text/logo #}
      <a class="navbar-brand" href="#">MyBraend</a>

      {# Collapsive button (toggler) #}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Uncollapse navigation">
        Biolog
      </button>

      {# Navigation in navigation bar #}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="#">
            Hi
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            Lol
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            Bar
          </a>
        </li>
      </ul>
    </nav>

  </body>

</html>

biologs/templates/biologs/create_biopost.html
{% extends "biologs/base.html" %}
{% load bootstrap4 %}

{% block header %}<h2>Create biopost</h2>{% endblock %}

{% block content %}

<form class="form" action="{% url 'biologs:create_biopost' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button class="btn btn-primary" name="Submit">
      Create & post!
    </button>
  {% endbuttons %}

</form>

{% endblock %}

biologs/templates/biologs/edit_biopost.html
{% extends "biologs/base.html" %}
{% load bootstrap4 %}

{% block header %}<h2>Edit biopost</h2>{% endblock %}

{% block content %}
<form class="form" action="{% url 'biologs:edit_biopost' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button class="btn btn-primary" name="Submit">
      Save changes
    </button>
  {% endbuttons %}
</form>
{% endblock %}

biologs/templates/biologs/index.html
{% extends "biologs/base.html" %}

{% block header %}
<div class="jumbotron">
  <h2 class="display-3">Biolog, the combination of biography and logging.</h2>

  <p class="lead"> Hello and welcome to the <a href="{% url 'biologs:home' %}">biolog.com</a>, the best blog-tacking website. This very simple website is very concentrated on the actual bioposts from the biosers. Also see <a href="{% url 'biologs:terminology' %}">terminology</a> page for information about words.</p>

  <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}">
    Register &raquo;
  </a>

  <a class="btn btn-lg btn-secondary" href="{% url 'users:login' %}">
    Log in &raquo;
  </a>

</div>
{% endblock header %}

{% block content %}
  <ul class="list-group">
    <li class="list-group-item active">Key features:</li>
    <li class="list-group-item">Main feed with tons of cool bioposts</li>
    <li class="list-group-item">Create, view and manage your biolog with its bioposts!</li>
    <li class="list-group-item">Subscribe to different biologs to have fun.</li>
    <li class="list-group-item">You can like bioposts that are really nice for you.</li>
    <li class="list-group-item">Leaving comments to the posts.</li>
    <li class="list-group-item">Markdown post writting.</li>
  </ul>
{% endblock %}

biologs/templates/biologs/terminology.html
{% extends "biologs/base.html" %}

{% block title %}Biolog terminology {% endblock %}
{% block header %}Biolog terminology webpage {% endblock %}

{% block content %}
<p>
Hi this a biologs terminology web page, here you can see what those used on the site words mean.
</p>
<ul>
  <li>Bioblog</li>
  <li>Biopost</li>
  <li>Bio</li>
  <li>Bioser</li>
  <li>Bike</li>
  <li>Bicom</li>
</ul>
{% endblock %}